# Generated by Django 4.2.7 on 2023-11-14 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MorePhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photo_folder/')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('Adopted', 'Adopted'), ('Pending', 'Pending'), ('Available', 'Available'), ('Withdrawn', 'Withdrawn')], max_length=10)),
                ('description', models.TextField(max_length=2500)),
                ('behavior', models.TextField(max_length=2000)),
                ('medicalHistory', models.TextField(max_length=2000)),
                ('specialNeeds', models.TextField(max_length=2000)),
                ('sex', models.IntegerField()),
                ('age', models.IntegerField()),
                ('breed', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=25)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=2)),
                ('species', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('fee', models.IntegerField()),
                ('photos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.morephotos')),
            ],
        ),
        migrations.AddField(
            model_name='morephotos',
            name='photos',
            field=models.ManyToManyField(blank=True, to='pet.photo'),
        ),
    ]
