# Generated by Django 4.2.7 on 2023-11-14 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='sex',
        ),
    ]
